# Generated by Django 5.2.9 on 2025-12-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoReciclaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('estado_llenado', models.IntegerField(default=0)),
                ('tipo_residuo', models.CharField(default='Vidrio', max_length=50)),
            ],
        ),
    ]
