# Generated by Django 5.2.9 on 2025-12-09 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoreciclaje',
            name='fecha_ultimo_vaciado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
