# Generated by Django 5.2.9 on 2025-12-16 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_puntoreciclaje_fecha_ultimo_vaciado'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoreciclaje',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
